name: Go Cover
on:
  push:
    paths:
      - 'go-cover/**'
jobs:
  go-cover:
    name: Test go-cover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Go Cover
        id: cover
        uses: ./go-cover
        with:
          path: ./go-cover/test
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ./go-cover/test/${{ steps.cover.outputs.coverage_report_file }}
